# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 10a64d9aa7a8ad2889cd638336ed424a0045ffb06fb13532db29db25e933c23c51334b3bada01da19aebf3af7ccc3be3301c343b3b679880821052f0b9f306f8

test:
  secret_key_base: c9312adaeedc154b129db79b837d74e26ae1b440f829a1813c33bab6ee6cedcfc997111de2d0781cb32f077d0bbba38c01d75084e546abda8ccc7b0e5ba2bb15

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
